# Generated by Django 2.2.1 on 2019-06-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190624_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='id_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='id_item',
            new_name='item',
        ),
    ]
